version: 2.1

orbs:
  python: circleci/python@2.1.1
  heroku: circleci/heroku@2.0.0
  docker: circleci/docker@2.2.0

jobs:
  build:

    docker:
      - image: cimg/python:3.9.4

    steps:
      - checkout
      - run:
          name: update pip
          command: python -m pip install --upgrade pip

      - run:
          name: Install Python Dependencies
          command: |
            python3 -m venv env
            . env/bin/activate && pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
      
      - run:
          name: PEP8 tests
          command: |
            . venv/bin/activate
            flake8

  build_push_docker_image:
    docker:
      - image: cimg/python:3.9.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push docker image
          command: |
            docker build -t anourry13/oc-lettings:$CIRCLE_SHA1 .
            echo $DOCKER_PASSWORD | docker login --username anourry13 --password-stdin
            docker push anourry13/oc-lettings:$CIRCLE_SHA1

  deploy-heroku:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a oc-lettings-web-app web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a oc-lettings-web-app web

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - build_push_docker_image:
          requires:
            - build
          filters:
            branches:
              only: main
      - deploy-heroku:
          requires:
            - build_push_docker_image
          filters:
            branches:
              only: main
