version: 2.1

orbs:
  python: circleci/python@2.1.1
  heroku: circleci/heroku@2.0.0
  docker: circleci/docker@2.2.0

jobs:
  build-and-tests:

    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            python -m pip install --upgrade pip
            pip install --user -r requirements.txt

      - run:
          name: Run tests
          command: |
            . env/bin/activate
            pytest
      
      - run:
          name: PEP8 tests
          command: |
            . env/bin/activate
            flake8

  build-push-docker-image:
    docker:
      - image: cimg/python:3.9.4

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push docker image
          command: |
            docker build -t $DOCKER_USERNAME/oc-lettings:$CIRCLE_SHA1 .
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
            docker push $DOCKER_USERNAME/oc-lettings:$CIRCLE_SHA1

  deploy-heroku:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker container to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set SECRET_KEY=${SECRET_KEY} -a ${HEROKU_APP_NAME}
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set SENTRY_DSN=${SENTRY_DSN} -a ${HEROKU_APP_NAME}
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a ${HEROKU_APP_NAME} web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a ${HEROKU_APP_NAME} web

workflows:
  build-and-deploy:
    jobs:
      - build-and-tests
      - build-push-docker-image:
          requires:
            - build-and-tests
      - deploy-heroku:
          requires:
            - build-push-docker-image
